// ─── Note Fund — Settings Page ─────────────────────────────────

import { showToast } from './utils.js'
import * as api from './api.js'

export async function renderSettings(container) {
  const settings = await api.getSettings()
  container.innerHTML = `<div class="settings-page"><div class="page-header"><div><h1>⚙️ Settings</h1><p class="page-subtitle">Make Note Fund work your way.</p></div></div><div class="settings-sections"><section class="settings-section"><div class="settings-section-heading"><span>🎨</span><div><h2>Appearance</h2><p>Customize how the app looks.</p></div></div><div class="settings-row"><div><strong>Theme</strong><span>Choose light or dark mode</span></div><div class="segmented-control"><button class="${settings.theme === 'light' ? 'active' : ''}" data-theme-choice="light">☀️ Light</button><button class="${settings.theme === 'dark' ? 'active' : ''}" data-theme-choice="dark">🌙 Dark</button></div></div></section><section class="settings-section"><div class="settings-section-heading"><span>🔔</span><div><h2>Notifications & Reminders</h2><p>Choose when Note Fund should alert you.</p></div></div><div class="settings-row"><div><strong>Browser notifications</strong><span>Get alerts about payments and balances</span></div><label class="switch"><input type="checkbox" id="notifications-enabled" ${settings.notificationsEnabled ? 'checked' : ''}><span></span></label></div><div class="settings-row"><div><strong>Reminders</strong><span>Show due dates and overdue balances</span></div><label class="switch"><input type="checkbox" id="reminders-enabled" ${settings.remindersEnabled ? 'checked' : ''}><span></span></label></div></section><section class="settings-section"><div class="settings-section-heading"><span>💾</span><div><h2>Data & Backup</h2><p>Keep a copy of your money records.</p></div></div><div class="settings-actions"><button class="settings-action" id="export-json"><span>📄</span><div><strong>Export JSON</strong><small>Complete backup of your data</small></div></button><button class="settings-action" id="export-csv"><span>📊</span><div><strong>Export CSV</strong><small>Open in spreadsheet apps</small></div></button><label class="settings-action"><span>📥</span><div><strong>Import Backup</strong><small>Restore a JSON backup</small></div><input type="file" id="import-backup" accept=".json,application/json" hidden></label></div></section><section class="settings-section"><div class="settings-section-heading"><span>🔗</span><div><h2>Connection</h2><p>Where your records are stored.</p></div></div><div class="connection-card"><span class="status-dot status-connected"></span><div><strong>Local storage connected</strong><span>Your data is saved securely in this browser.</span></div></div><div class="connection-note">Google Sheets sync can be enabled by adding your Apps Script web app URL in the data layer.</div></section></div></div>`

  document.querySelectorAll('[data-theme-choice]').forEach(button => button.addEventListener('click', async () => { const theme = button.dataset.themeChoice; await api.updateSettings({ theme }); document.documentElement.setAttribute('data-theme', theme); document.querySelectorAll('[data-theme-choice]').forEach(b => b.classList.toggle('active', b.dataset.themeChoice === theme)); const icon = document.getElementById('theme-icon'); if (icon) icon.textContent = theme === 'dark' ? '🌙' : '☀️'; showToast(`Switched to ${theme} mode`) }))
  document.getElementById('notifications-enabled').addEventListener('change', e => api.updateSettings({ notificationsEnabled: e.target.checked }))
  document.getElementById('reminders-enabled').addEventListener('change', e => api.updateSettings({ remindersEnabled: e.target.checked }))
  document.getElementById('export-json').addEventListener('click', async () => download(await api.exportData(), 'note-fund-backup.json', 'application/json'))
  document.getElementById('export-csv').addEventListener('click', async () => download(await api.exportCSV(), 'note-fund-data.csv', 'text/csv'))
  document.getElementById('import-backup').addEventListener('change', async e => { const file = e.target.files[0]; if (!file) return; try { await api.importData(await file.text()); showToast('Backup restored successfully.'); window.location.reload() } catch { showToast('That backup file could not be imported.', 'error') } })
}

function download(content, filename, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url) }
